simplify gh-action for tox

diff --git a/.github/workflows/run_tox.yml b/.github/workflows/run_tox.yml
--- a/.github/workflows/run_tox.yml
+++ b/.github/workflows/run_tox.yml
@@ -15,15 +15,16 @@ jobs:
     env:
       USING_COVERAGE: '3.8'
 
-    strategy:
-      matrix:
-        python-version: ["3.6", "3.7", "3.8", "3.9"]
+#    strategy:
+#      matrix:
+#        python-version: ["3.6", "3.7", "3.8", "3.9"]
 
     steps:
       - uses: "actions/checkout@v2"
       - uses: "actions/setup-python@v1"
         with:
-          python-version: "${{ matrix.python-version }}"
+          # python-version: "${{ matrix.python-version }}"
+          python-version: "3.8"
       - name: "Install dependencies"
         run: |
           set -xe
@@ -34,14 +35,14 @@ jobs:
       - name: "Run tox targets for ${{ matrix.python-version }}"
         run: "python -m tox"
 
-      - name: "Get coverage"
-        run: |
-          set -xe
-          python -m coverage combine
-          python -m coverage xml
-        if: "contains(env.USING_COVERAGE, matrix.python-version)"
-      - name: Upload coverage to Codecov
-        if: "contains(env.USING_COVERAGE, matrix.python-version)"
-        uses: "codecov/codecov-action@v1"
-        with:
-          fail_ci_if_error: true
+#      - name: "Get coverage"
+#        run: |
+#          set -xe
+#          python -m coverage combine
+#          python -m coverage xml
+#        if: "contains(env.USING_COVERAGE, matrix.python-version)"
+#      - name: Upload coverage to Codecov
+#        if: "contains(env.USING_COVERAGE, matrix.python-version)"
+#        uses: "codecov/codecov-action@v1"
+#        with:
+#          fail_ci_if_error: true
